name: Arch machine compiler
on:
  workflow_dispatch:

jobs:
  kernel_compiler:
    runs-on: ubuntu-latest
    container:
      image: archlinux/archlinux:base-devel
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup depencies and Toolchain
        run: |
          curl -LSs "https://raw.githubusercontent.com/${{ github.repository_owner }}/linux_playground/refs/heads/main/toolchain.sh" | bash
