name: Arch machine compiler
on:
  workflow_dispatch:

jobs:
  arch-job:
    runs-on: ubuntu-latest
    container:
      image: archlinux/archlinux:base-devel
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup depencies and Toolchain
        run: |
          OWNER="${{ github.repository_owner }}"
          curl -LSs "https://raw.githubusercontent.com/{OWNER}/linux_playground/refs/heads/main/kernel.sh" | bash
